-- MySQL Script generated by MySQL Workbench
-- Wed Apr 28 21:17:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GLP_alpha_1.1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GLP_alpha_1.1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GLP_alpha_1.1` ;
USE `GLP_alpha_1.1` ;

-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`leagues` (
  `lid` INT NOT NULL AUTO_INCREMENT,
  `lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lid`, `lname`),
  UNIQUE INDEX `lname_UNIQUE` (`lname` ASC) VISIBLE,
  UNIQUE INDEX `lid_UNIQUE` (`lid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`teams` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `League_lid` VARCHAR(45) NOT NULL,
  `tabbrv` VARCHAR(5) NOT NULL,
  `tname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tid`, `League_lid`, `tname`),
  UNIQUE INDEX `tid_UNIQUE` (`tid` ASC) VISIBLE,
  INDEX `teams_lid_lid_FK_idx` (`League_lid` ASC) VISIBLE,
  UNIQUE INDEX `tname_UNIQUE` (`tname` ASC) VISIBLE,
  CONSTRAINT `teams_lid_lid_FK`
    FOREIGN KEY (`League_lid`)
    REFERENCES `GLP_alpha_1.1`.`leagues` (`lname`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`users` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`players` (
  `pname` VARCHAR(45) NOT NULL,
  `pusername` VARCHAR(45) NULL,
  `Teams_tid` VARCHAR(45) NOT NULL,
  `pDOB` DATE NULL,
  `jerseyNo` INT NULL,
  `ppos` ENUM("GK", "FW") NOT NULL,
  `prole` ENUM("Player", "Coach", "Owner") NOT NULL,
  PRIMARY KEY (`pname`, `Teams_tid`),
  UNIQUE INDEX `pusername_UNIQUE` (`pusername` ASC) VISIBLE,
  INDEX `players_Teams_tname_tname_FK_idx` (`Teams_tid` ASC) VISIBLE,
  CONSTRAINT `pusername_pusername_FK`
    FOREIGN KEY (`pusername`)
    REFERENCES `GLP_alpha_1.1`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `players_Teams_tname_tname_FK`
    FOREIGN KEY (`Teams_tid`)
    REFERENCES `GLP_alpha_1.1`.`teams` (`tname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`calendar` (
  `round` VARCHAR(20) NOT NULL,
  `date` DATE NOT NULL,
  `cal_tname_home` VARCHAR(45) NOT NULL,
  `cal_tname_away` VARCHAR(45) NOT NULL,
  `cal_league_lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`round`, `date`, `cal_tname_home`, `cal_tname_away`, `cal_league_lname`),
  INDEX `cal_tname_away_tname_FK_idx` (`cal_tname_away` ASC) VISIBLE,
  INDEX `cal_league_lname_lname_FK_idx` (`cal_league_lname` ASC) VISIBLE,
  INDEX `cal_tname_home_tname_FK_idx` (`cal_tname_home` ASC) VISIBLE,
  CONSTRAINT `cal_tname_home_tname_FK`
    FOREIGN KEY (`cal_tname_home`)
    REFERENCES `GLP_alpha_1.1`.`teams` (`tname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cal_tname_away_tname_FK`
    FOREIGN KEY (`cal_tname_away`)
    REFERENCES `GLP_alpha_1.1`.`teams` (`tname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cal_league_lname_lname_FK`
    FOREIGN KEY (`cal_league_lname`)
    REFERENCES `GLP_alpha_1.1`.`teams` (`League_lid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`league_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`league_table` (
  `Teams_tname` VARCHAR(45) NOT NULL,
  `gamesPlayed` INT NOT NULL DEFAULT 0,
  `W` INT NOT NULL DEFAULT 0,
  `D` INT NOT NULL DEFAULT 0,
  `L` INT NOT NULL DEFAULT 0,
  `goalsScored` INT NOT NULL DEFAULT 0,
  `goalsConceded` INT NOT NULL DEFAULT 0,
  `goalDIfference` BIGINT NOT NULL DEFAULT 0,
  `Pts` INT NOT NULL DEFAULT 0,
  `lname` VARCHAR(45) NOT NULL,
  `round` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Teams_tname`, `lname`),
  INDEX `lt_lname_lname_FK_idx` (`lname` ASC) VISIBLE,
  INDEX `lt_round_round_FK_idx` (`round` ASC) VISIBLE,
  UNIQUE INDEX `Teams_tname_UNIQUE` (`Teams_tname` ASC) VISIBLE,
  CONSTRAINT `lt_Teams_tname_tname_FK`
    FOREIGN KEY (`Teams_tname`)
    REFERENCES `GLP_alpha_1.1`.`teams` (`tname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lt_lname_lname_FK`
    FOREIGN KEY (`lname`)
    REFERENCES `GLP_alpha_1.1`.`calendar` (`cal_league_lname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lt_round_round_FK`
    FOREIGN KEY (`round`)
    REFERENCES `GLP_alpha_1.1`.`calendar` (`round`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`match_forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`match_forms` (
  `mf_id` INT NOT NULL AUTO_INCREMENT,
  `mf_tname` VARCHAR(45) NOT NULL,
  `mf_round` VARCHAR(45) NOT NULL,
  `pname_GK` VARCHAR(45) NULL,
  `pname_FW1` VARCHAR(45) NULL,
  `pname_FW2` VARCHAR(45) NULL,
  `pname_FW3` VARCHAR(45) NULL,
  `startDate` VARCHAR(45) NULL,
  `endDate` VARCHAR(45) NULL,
  PRIMARY KEY (`mf_id`, `mf_tname`, `mf_round`),
  UNIQUE INDEX `mf_id_UNIQUE` (`mf_id` ASC) VISIBLE,
  INDEX `mf_tname_tname_FK_idx` (`mf_tname` ASC) VISIBLE,
  INDEX `mf_round_round_FK_idx` (`mf_round` ASC) VISIBLE,
  INDEX `pname_GK_pname_FK_idx` (`pname_GK` ASC) VISIBLE,
  INDEX `pname_FW1_pname_FK_idx` (`pname_FW1` ASC) VISIBLE,
  INDEX `pname_FW2_pname_FK_idx` (`pname_FW2` ASC) VISIBLE,
  INDEX `pname_FW3_pname_FK_idx` (`pname_FW3` ASC) VISIBLE,
  CONSTRAINT `mf_tname_tname_FK`
    FOREIGN KEY (`mf_tname`)
    REFERENCES `GLP_alpha_1.1`.`teams` (`tname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `mf_round_round_FK`
    FOREIGN KEY (`mf_round`)
    REFERENCES `GLP_alpha_1.1`.`calendar` (`round`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pname_GK_pname_FK`
    FOREIGN KEY (`pname_GK`)
    REFERENCES `GLP_alpha_1.1`.`players` (`pname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pname_FW1_pname_FK`
    FOREIGN KEY (`pname_FW1`)
    REFERENCES `GLP_alpha_1.1`.`players` (`pname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pname_FW2_pname_FK`
    FOREIGN KEY (`pname_FW2`)
    REFERENCES `GLP_alpha_1.1`.`players` (`pname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pname_FW3_pname_FK`
    FOREIGN KEY (`pname_FW3`)
    REFERENCES `GLP_alpha_1.1`.`players` (`pname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`match_forms_FW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`match_forms_FW` (
  `mf_FW_id` INT NOT NULL AUTO_INCREMENT,
  `mf_FW_round` VARCHAR(20) NOT NULL,
  `mf_FW_tname` VARCHAR(45) NOT NULL,
  `FW_pname` VARCHAR(45) NOT NULL,
  `FW_match1_ht` VARCHAR(45) NULL,
  `FW_match1_at` VARCHAR(45) NULL,
  `FW_match1_ht_score` INT NULL,
  `FW_match1_at_score` INT NULL,
  `FW_match2_ht` VARCHAR(45) NULL,
  `FW_match2_at` VARCHAR(45) NULL,
  `FW_mathc2_ht_score` INT NULL,
  `FW_mathc2_at_score` INT NULL,
  `FW_goals` INT NULL,
  PRIMARY KEY (`mf_FW_id`, `mf_FW_round`, `mf_FW_tname`, `FW_pname`),
  UNIQUE INDEX `mfr_id_UNIQUE` (`mf_FW_id` ASC) VISIBLE,
  INDEX `mf_FW_pname_pname_FK_idx` (`FW_pname` ASC) VISIBLE,
  INDEX `mf_FW_round_round_FK_idx` (`mf_FW_round` ASC) VISIBLE,
  INDEX `mf_FW_tname_tname_FK_idx` (`mf_FW_tname` ASC) VISIBLE,
  CONSTRAINT `mf_FW_round_round_FK`
    FOREIGN KEY (`mf_FW_round`)
    REFERENCES `GLP_alpha_1.1`.`match_forms` (`mf_round`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `mf_FW_tname_tname_FK`
    FOREIGN KEY (`mf_FW_tname`)
    REFERENCES `GLP_alpha_1.1`.`match_forms` (`mf_tname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mf_FW_pname_pname_FK`
    FOREIGN KEY (`FW_pname`)
    REFERENCES `GLP_alpha_1.1`.`players` (`pname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`match_forms_GK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`match_forms_GK` (
  `mf_GK_id` INT NOT NULL AUTO_INCREMENT,
  `mf_GK_round` VARCHAR(20) NOT NULL,
  `mf_GK_tname` VARCHAR(45) NOT NULL,
  `GK_pname` VARCHAR(45) NOT NULL,
  `GK_match1_ht` VARCHAR(45) NULL,
  `GK_match1_at` VARCHAR(45) NULL,
  `GK_match1_ht_score` INT NULL,
  `GK_match1_at_score` INT NULL,
  `GK_match2_ht` VARCHAR(45) NULL,
  `GK_match2_at` VARCHAR(45) NULL,
  `GK_match2_ht_score` INT NULL,
  `GK_match2_at_score` INT NULL,
  `GK_match3_ht` VARCHAR(45) NULL,
  `GK_match3_at` VARCHAR(45) NULL,
  `GK_match3_ht_score` INT NULL,
  `GK_match3_at_score` INT NULL,
  `GK_match4_ht` VARCHAR(45) NULL,
  `GK_match4_at` VARCHAR(45) NULL,
  `GK_match4_ht_score` INT NULL,
  `GK_match4_at_score` INT NULL,
  `GK_match5_ht` VARCHAR(45) NULL,
  `GK_match5_at` VARCHAR(45) NULL,
  `GK_match5_ht_score` INT NULL,
  `GK_match5_at_score` INT NULL,
  `GK_match6_ht` VARCHAR(45) NULL,
  `GK_match6_at` VARCHAR(45) NULL,
  `GK_match6_ht_score` INT NULL,
  `GK_match6_at_score` INT NULL,
  `GK_saves` INT NULL,
  PRIMARY KEY (`mf_GK_id`, `mf_GK_round`, `mf_GK_tname`, `GK_pname`),
  UNIQUE INDEX `mf_GK_id_UNIQUE` (`mf_GK_id` ASC) VISIBLE,
  INDEX `mf_GK_round_round_FK_idx` (`mf_GK_round` ASC) VISIBLE,
  INDEX `mf_GK_tname_tname_FK_idx` (`mf_GK_tname` ASC) VISIBLE,
  INDEX `mf_GK_pname_pname_FK_idx` (`GK_pname` ASC) VISIBLE,
  CONSTRAINT `mf_GK_round_round_FK`
    FOREIGN KEY (`mf_GK_round`)
    REFERENCES `GLP_alpha_1.1`.`calendar` (`round`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `mf_GK_tname_tname_FK`
    FOREIGN KEY (`mf_GK_tname`)
    REFERENCES `GLP_alpha_1.1`.`teams` (`tname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mf_GK_pname_pname_FK`
    FOREIGN KEY (`GK_pname`)
    REFERENCES `GLP_alpha_1.1`.`players` (`pname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`football_matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`football_matches` (
  `fmatch_round` VARCHAR(20) NOT NULL,
  `fmatch_ht` VARCHAR(45) NOT NULL,
  `fmatch_at` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`fmatch_round`, `date`),
  INDEX `fmatch_round_idx` (`fmatch_round` ASC) VISIBLE,
  INDEX `fmatch_ht_idx` (`fmatch_ht` ASC) INVISIBLE,
  INDEX `fmatch_at_idx` (`fmatch_at` ASC) VISIBLE,
  CONSTRAINT `fmatch_round`
    FOREIGN KEY (`fmatch_round`)
    REFERENCES `GLP_alpha_1.1`.`calendar` (`round`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GLP_alpha_1.1`.`football_matches_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GLP_alpha_1.1`.`football_matches_results` (
  `fmr_round` VARCHAR(20) NOT NULL,
  `fmr_ht` VARCHAR(45) NOT NULL,
  `fmr_at` VARCHAR(45) NOT NULL,
  `fmr_ht_score` INT NOT NULL,
  `fmr_at_score` INT NOT NULL,
  PRIMARY KEY (`fmr_round`, `fmr_ht`, `fmr_at`),
  INDEX `fmr_ht_ht_FK_idx` (`fmr_ht` ASC) VISIBLE,
  INDEX `fmr_at_at_FK_idx` (`fmr_at` ASC) VISIBLE,
  CONSTRAINT `fmr_round_round_FK`
    FOREIGN KEY (`fmr_round`)
    REFERENCES `GLP_alpha_1.1`.`football_matches` (`fmatch_round`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fmr_ht_ht_FK`
    FOREIGN KEY (`fmr_ht`)
    REFERENCES `GLP_alpha_1.1`.`football_matches` (`fmatch_ht`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fmr_at_at_FK`
    FOREIGN KEY (`fmr_at`)
    REFERENCES `GLP_alpha_1.1`.`football_matches` (`fmatch_at`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
